greeting:
    message: "hello"

quarkus:
    mongodb:
        database: "admin"
        connection-string: "mongodb://root:root@mongo:27017"
    redis:
        hosts: "redis://redis:6379"

"%dev":
    quarkus:
        mongodb:
            database: "admin"
            connection-string: "mongodb://root:root@localhost:27017"
        redis:
            hosts: "redis://localhost:6379"

"%test":
    quarkus:
        mongodb:
            database: "admin"
            connection-string: "mongodb://root:root@localhost:27017"
        redis:
            hosts: "redis://localhost:6379"

