spring:
    jpa:
        hibernate:
            ddl-auto: update
    data:
        mongodb:
            database: admin
            host: localhost
            port: 27017
            username: root
            password: root
