quarkus:
    datasource:
        db-kind: "postgresql"
        jdbc:
            url: "jdbc:postgresql://postgres:5432/quarkus"
        username: "postgres"
        password: "postgres"
    http:
        root-path: "/api"




"%dev":
    quarkus:
        datasource:
            db-kind: "postgresql"
            jdbc:
                url: "jdbc:postgresql://localhost:5432/quarkus"
            username: "postgres"
            password: "postgres"
        hibernate-orm:
            database:
                generation: "update"

    hibernate-orm:
        log:
            sql: true
