spring:
    data:
        mongodb:
            database: admin
            host: localhost
            port: 27017
            username: root
            password: root

    redis:
        host: localhost
        port: 6379
logging:
    level:
        root: info