version: "2.0"

services:

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"

volumes:
    mongo_data:

