version: "2.0"

services:

    free-movie-server:
        image: 934622645/free-movie-server
        restart: unless-stopped
        expose:
            - "80:8080"

    mongo:
        image: mongo
        restart: always
        volumes:
            -   mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

volumes:
    mongo_data:

