version: "2.0"

services:

    free-movie-server:
        image: 934622645/free-movie-server
        restart: unless-stopped
        expose:
            - "80:8080"

    mysql:
        image: mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "free_movie"

